FROM oven/bun:1

ARG DB_URL

WORKDIR /usr/src/app

# Copy everything from the context (which is ./week-27.2)
COPY . .

# Install dependencies
RUN bun install --frozen-lockfile

# Generate Prisma client
RUN bun run generate:db

# Build Next.js frontend
RUN DB_URL=$DB_URL bunx turbo build --filter=web...

EXPOSE 3000

CMD ["bun", "start:frontend"]
